# Generated by Django 4.2.1 on 2023-06-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11)),
                ('present_address', models.CharField(max_length=300)),
                ('permanent_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, default='')),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('rents_for', models.CharField(choices=[('F', 'For Family'), ('B', 'For Bachelors'), ('O', 'For Office')], default='F', max_length=2)),
                ('numbers_of_beds', models.PositiveSmallIntegerField()),
                ('numbers_of_bath', models.PositiveSmallIntegerField()),
                ('drawing_room_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('dining_room_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('kitchen_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('rental_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11)),
                ('present_address', models.CharField(max_length=300)),
                ('permanent_address', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('LL', 'Landlord'), ('R', 'Renter')], default='R', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord_ProfileImage',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('Landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_app.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Renter_ProfileImage',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('Renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_created=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trxID', models.CharField(max_length=100)),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.landlord')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_created=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
        migrations.AddField(
            model_name='renter',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.user'),
        ),
        migrations.CreateModel(
            name='Property_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.user'),
        ),
    ]
