# Generated by Django 4.2.4 on 2023-08-24 22:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('L', 'Landlord'), ('R', 'Renter')], default='A', max_length=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11)),
                ('present_address', models.CharField(blank=True, max_length=300, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=300, null=True)),
                ('area', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_created=True, editable=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('rents_for', multiselectfield.db.fields.MultiSelectField(choices=[('F', 'For Family'), ('B', 'For Bachelors'), ('O', 'For Office')], default='F', max_length=10)),
                ('numbers_of_beds', models.PositiveSmallIntegerField()),
                ('numbers_of_bath', models.PositiveSmallIntegerField()),
                ('drawing_room_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('dining_room_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('kitchen_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('rental_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11)),
                ('present_address', models.CharField(blank=True, max_length=300, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=300, null=True)),
                ('area', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord_ProfileImage',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('Landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_app.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Renter_ProfileImage',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('Renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_created=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trxID', models.CharField(max_length=100)),
                ('Landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.landlord')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_created=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
            ],
        ),
    ]
