# Generated by Django 4.2.1 on 2023-06-26 22:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_property',
            name='post_date',
            field=models.DateField(auto_created=True, editable=False),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='rents_for',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'For Family'), ('B', 'For Bachelors'), ('O', 'For Office')], default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
    ]
