# Generated by Django 4.2.4 on 2023-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter_profileimage',
            name='Renter',
        ),
        migrations.AddField(
            model_name='landlord',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='renter',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Landlord_ProfileImage',
        ),
        migrations.DeleteModel(
            name='Renter_ProfileImage',
        ),
    ]
