# Generated by Django 4.2.4 on 2023-08-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_landlord_city_renter_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='city',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='city',
        ),
        migrations.AddField(
            model_name='landlord',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='renter',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
    ]
