# Generated by Django 4.2.4 on 2023-08-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_remove_landlord_city_remove_renter_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='renter',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
