# Generated by Django 4.2.4 on 2023-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_alter_renter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='landlord',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile/profile_images/'),
        ),
    ]
