# Generated by Django 4.2.4 on 2023-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0007_district_alter_landlord_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
