# Generated by Django 4.2.4 on 2023-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0009_alter_renter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_property',
            name='rent_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
