# Generated by Django 4.2.4 on 2023-09-11 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0010_rental_property_rent_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter'),
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=400)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rental_Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.rental_property')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.renter')),
            ],
        ),
    ]
