# Generated by Django 4.2.4 on 2023-09-11 19:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0011_alter_review_renter_responses_notification_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_property',
            name='electric_meter_type',
            field=models.CharField(default='Post-paid', max_length=10),
        ),
        migrations.AddField(
            model_name='rental_property',
            name='gass_type',
            field=models.CharField(default='Pre-paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='dining_room_status',
            field=models.CharField(default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='drawing_room_status',
            field=models.CharField(default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='kitchen_status',
            field=models.CharField(default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='rental_status',
            field=models.CharField(default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='rents_for',
            field=multiselectfield.db.fields.MultiSelectField(default='FAMILY', max_length=10),
        ),
    ]
