# Generated by Django 4.2.4 on 2023-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0012_rental_property_electric_meter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_property',
            name='apartment_area',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
