# Generated by Django 4.2.4 on 2023-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0013_rental_property_apartment_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_property',
            name='area_unit',
            field=models.CharField(default='sq-ft', max_length=10),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='post_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
