# Generated by Django 4.2.4 on 2023-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0014_rental_property_area_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_property',
            name='gass_type',
            field=models.CharField(default='Pre-paid Meter', max_length=17),
        ),
    ]
