# Generated by Django 4.2.4 on 2023-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0015_alter_rental_property_gass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_property',
            name='electric_meter_type',
            field=models.CharField(default='Post-paid Meter', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='gass_type',
            field=models.CharField(default='Pre-paid Gas Meter', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='kitchen_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='rental_status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
