# Generated by Django 4.2.4 on 2023-09-15 23:33

from django.db import migrations, models
import rental_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0016_alter_rental_property_electric_meter_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=rental_app.models.Property_Image.upload_path),
        ),
        migrations.AlterField(
            model_name='rental_property',
            name='post_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
